### ISSUE TITLE
update to work with new python-trezor

### ISSUE THREAD

**Issue by prusnak** [pooler/electrum-ltc#201]
An update is required for electrum-ltc to work with new python-trezor library. Upstream electrum already has these changes.

```
    Incompatible Trezor library detected.
    (Original error: Function has been moved to btc.get_public_node)
```

**Comment by pooler** [comment]
Any upstream changes should already have been merged. Does this issue affect the current master branch? If so, could you point out what changes are needed?

**Comment by prusnak** [comment]
No idea, it was reported here: https://www.reddit.com/r/TREZOR/comments/a8iqe1/trezor_to_electrum_connection_wont_work_linux/

You can assume the user is not using master, but rather a latest released version.

**Comment by pooler** [comment]
Closing, as this should be fixed in the most recent binary release.

**Comment by bosomt** [comment]
@prusnak i tried Latest Release: 3.3.6.1 (released 2019-05-22)
with Mint linux and installed latest libraries.
Still broken in electrum-ltc
