### ISSUE TITLE
Issues with regards to transaction fees

### ISSUE THREAD

**Issue by Zero3** [pooler/electrum-ltc#24]
I'm casually trying out Litecoin and Electrum-LTC and am running into some issues with regards to transaction fees.

To get myself started, I obtained ~2 mLTC from online faucets. I suspect a significant amount of people do this before spending real money on LTC. I then attempted to send 1 mLTC to a friend to show him what this cryptocurrency was all about. However, Electrum-LTC won't let me to do this:

    This transaction requires a higher fee, or it will not be propagated by the network.

I see several issues here:

**1) The error is not very user-friendly and frankly quite confusing. The GUI didn't even mention transaction fees, and now it is complaining about them, as if I did something wrong. At this point I had no idea what to do differently, since all I did was specifying a receiver address and an amount to transfer.**

Peeking around in the settings, I realize that Electrum-LTC calculates a transaction fee by default. So the next issue is:

**2) When Electrum-LTC calculates the transaction fee automatically, it shouldn't contradict itself by refusing it afterwards.**

With the automatic fee calculation not working, I enabled the visibility of the fee field and tried setting it myself. No matter how high I set it (within my very limited funds), I got the same error. This leads me to:

**3) When Electrum-LTC refuses the fee, it should help the user to select a valid fee. This could be by updating the fee field with an acceptable value, or at least telling the user what value it considers acceptable. At the moment, the user has to repeatedly guess higher and higher until he hits whatever fee Electrum-LTC considers acceptable.**

I feel like I have tried everything reasonable to make Electrum-LTC send my money, without luck. Maybe this has something to do with the very small amount of money I'm trying to send, but Electrum-LTC is not being very helpful in making me understand what the problem is.

Based on my experience so far, I'm ready to uninstall Electrum-LTC. I want it to work though, so let me know if this is my own fault and I can do something to fix this, or if I can be of any help in debugging these issues.

**Comment by pooler** [comment]
Thank you for your detailed feedback.
The issues you describe should be fixed by commit 0a4ed1a, which will be included in the upcoming 2.4.* versions of Electrum-LTC.

**Comment by MrMebelMan** [comment]
Looks like the issue wasn't fixed. My Electrum-LTC v3.0.6.2 is refusing to send a tx with a fee less than 0.00023, and then it gives me the warning about the unusually high tx fee.
