### ISSUE TITLE
Error - offline transaction - "Electrum was unable to parse your transaction"

### ISSUE THREAD

**Issue by JW8888** [pooler/electrum-ltc#69]
Using Electrum LTC to send from cold storage/offline. After signing transaction, loaded signed file into watching wallet and error message comes up:

"Electrum was unable to parse your transaction"

Using Version 2.8.3.5 on Ubuntu 16.04

Appreciate any help, as I'm unable to move LTC at all at the moment, thanks!

**Comment by pooler** [comment]
This should be fixed in 2.9.3.1, please give it a try.

**Comment by JW8888** [comment]
Hi, thanks for your reply
Updated both the online, and offline electrum-ltc, to 2.9.3.1, but still experienced the same error message. Trying to load the transaction from text - that has been obtained after scanning qr code, process works with electrum for bitcoin, but not here..!

**Comment by pooler** [comment]
I tried to reproduce your issue but I didn't get any error message. Could you please describe the procedure you followed step by step? Also, for comparison, what version of Electrum for Bitcoin are you using?

**Comment by JW8888** [comment]
Electrum for bitcoin = 2.6.4 : thinking about this - only difference is I have electrum for android & procedure works after scanning qr code, but don't have android version for electrum ltc, so have to use slightly different process as below:

_________
Procedure:

(from online - watching only wallet - electrum-ltc 2.9.3.1)
create transaction - save to file.txn

reboot to same ubuntu but from live dvd session
install electrum ltc 2.9.3.1 & restore wallet from seed
load transaction from file
go offline
sign transaction
scan qr code with phone & save text

kill session - wait & then reboot to regular installation ubuntu/electrum
load transaction from text
at this point meet error 'unable to parse...'

hope all makes sense...

**Comment by pooler** [comment]
I see. I think the problem is that you're entering the raw QR-code data, which is base-43 encoded, but that encoding is not supported by the "load transaction from text" dialog. Could you please try converting the QR-code data to hex using [this tool](http://electrum43.org/) before entering it into the dialog?

**Comment by JW8888** [comment]
Hi,
ok, its working
re: 'base-43 encoded, but that encoding is not supported by the "load transaction from text" dialog'
I had no idea about this at all, I had no appreciation that the format from the QR code would not be correct...
...thanks very much for your help, apologies for bringing up a non-issue..!

**Comment by pooler** [comment]
You're welcome! :)
